### ISSUE TITLE
A similar canvas solution(Quamolit) here

### ISSUE THREAD

**Issue by jiyinyiyong** [Flipboard/react-canvas#10]
I'm very interested in this project since I was trying is a similar approach named Quamolit here:
https://github.com/Quamolit
Project Quamolit is not yet done. Actually I'm feeling quite stressful to push it forward due to transitions.
Anyway here's what I think on declarative programming based on canvas:

### Why use canvas

I made an expriment before with React Animations(http://repo.cirru.org/fractal-editor/index.html) but got such a conclusion:

* DOM manipulations(sort) will break CSS transitions, so DOM is not the best solution for animations. Especally when there's a lot of animations. https://dribbble.com/shots/1912396-Jumping-loader

### My solution

So I created Quamolit, in which each element has it unique id, and its internal state. Then even after sorting, given one element is not destroyed, it will just make transition to its new position or state.
In such way, an element can even jump to another branch if its id stays.

Meanwhile, in elements' lifecycles, there are 'delay', 'entering', 'stable', 'changing', 'postpone', 'leaving'. In most of these periods, there are transitions. By doing this, I think creating animations can be much easier.

At last I took a solution which is quite different with React in syntax. Here's an early example:

https://github.com/Quamolit/todolisting/blob/master/src/app/container.coffee
```coffee
module.exports = Quamolit.createComponent
  name: 'container'

  stores:
    todos: [todoStore, 'all']

  getInitialState: -> text: ''

  getKeyframe: -> x: 0, y: 0
  getEnteringKeyframe: -> x: -40, y: 0
  getLeavingKeyframe: ->
    @getEnteringKeyframe()

  render: ->
    header = [
      handler {x: 0, y: -140}, {}
    ]

    items = @state.todos.map (data, index) =>
      order = index
      line {x: 0, y: (80 * order - 80)}, {data: data, id: "line.#{data.id}", isComposing: false}

    header.concat items
```

I'm not sure if that helps react-canvas. Just want to say I'm really interested in such solutions on programming in canvas.

**Comment by mjohnston** [comment]
Thanks for sharing, Quamolit looks very interesting!

I know there is a lot of work going on around how to better handle animations in React. cc: @chenglou

**Comment by chenglou** [comment]
React-tween-state should just work with react-canvas. If you guys have other interesting ways to achieve the same result, please do ping me =)

**Comment by mjohnston** [comment]
Yes - I think react-tween-state is actually the perfect animation model for react-canvas. Would love to investigate a possible integration here.

**Comment by chenglou** [comment]
(I'm @_chenglou on Twitter) cool. Would love some feedback. There hasn't been perf complains but there are room left for optimizations

**Comment by mjohnston** [comment]
https://github.com/Flipboard/react-canvas/issues/21

**Comment by jiyinyiyong** [comment]
Yes, React-tween-state is great and I was using it in the project I mentioned above too. But I want the `tweenState`'s code to be shorter in my project.
https://github.com/Cirru/cirru-fractal-editor/blob/master/coffee/components/line.coffee#L6

Glad to hear react-canvas is start working on things related to animations.
