### ISSUE TITLE
Can not resolve 'fs' in module 'linebreak'

### ISSUE THREAD

**Issue by differui** [Flipboard/react-canvas#102]
The linebreaker require 'fs' form native Node.js:

```
# src/linebreaker.coffee
UnicodeTrie = require 'unicode-trie'
fs = require 'fs'
base64 = require 'base64-js'
```

But webpack seems not support native Node.js module:

```
ERROR in ./~/react-canvas/~/linebreak/src/linebreaker.js
Module not found: Error: Cannot resolve module 'fs' in /Users/rui/Sandbox/react-canvas-layout.test/node_modules/react-canvas/node_modules/linebreak/src
resolve module fs in /Users/rui/Sandbox/react-canvas-layout.test/node_modules/react-canvas/node_modules/linebreak/src
```

I am trying to use browserify instead of webpack.

**Comment by github302** [comment]
I have the same problems too!

**Comment by differui** [comment]
#7

**Comment by awc737** [comment]
This is still an issue for me, I included brfs and have the latest dependencies:

ERROR in ./~/linebreak/src/linebreaker.js
Module not found: Error: Cannot resolve module 'fs' in /home/alex/dev/games/phaser/webpack-thrustjam/node_modules/linebreak/src
 @ ./~/linebreak/src/linebreaker.js 7:7-20

**Comment by leedium** [comment]
Yes, getting same issue as well
ERROR in ./~/react-canvas/~/linebreak/src/linebreaker.js
Module not found: Error: Cannot resolve module 'fs' in /Users/david.lee/Sites/redux/examples/counter/node_modules/react-canvas/node_modules/linebreak/src
 @ ./~/react-canvas/~/linebreak/src/linebreaker.js 7:7-20

**Comment by SalahAdDin** [comment]
:+1:

**Comment by jhudson8** [comment]
same issue here with 1.0 release... any fix in sight?

**Comment by tuxracer** [comment]
Do you have a link to a repo this can be reproduced on? I cannot reproduce this.

**Comment by jhudson8** [comment]
I don't - I deleted it.  I ended up not using this project.  But it was a simple webpack install and literally all I did was added react-canvas to the package.json.

**Comment by tuxracer** [comment]
Got it. Well for others you'll need to install the [brfs](https://github.com/substack/brfs) transform.

```bash
npm install -g brfs
npm install --save-dev transform-loader brfs
```

Then add the [brfs](https://github.com/substack/brfs) transform to your webpack config [example](https://github.com/Flipboard/react-canvas/blob/master/webpack.config.js#L22)

```javascript
module: {
  postLoaders: [
    { loader: "transform?brfs" }
  ]
}
```

**Comment by adamflorin** [comment]
I also had to add the Webpack loader mentioned by @andrewho83 in #110. It's working now!

**Comment by BHouwens** [comment]
I'm still getting issues, but have the babel-loader in addition to the transform-loader required here. Is there something I'm missing?

**Comment by tuxracer** [comment]
@BHouwens the brfs loader mentioned here https://github.com/Flipboard/react-canvas#using-with-webpack ?

**Comment by BHouwens** [comment]
That's the one yeah
