### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by andrewho83** [Flipboard/react-canvas#110]
I'm using webpack along with react-canvas and the most recent changes have broken my build.  Has anyone been able to build?

**Comment by andrewho83** [comment]
Not sure if this is related, but I had to fix this by adding this to my config:

```
{
              test: /\.js$/,
              include: /linebreak/,
              loader: "transform?brfs"
}
```

**Comment by tuxracer** [comment]
Relates to https://github.com/Flipboard/react-canvas/blob/master/webpack.config.js#L22 and #114
