### ISSUE TITLE
Package limitations

### ISSUE THREAD

**Issue by arnaud** [Flipboard/react-canvas#114]
Hi,
Are there any known integration limitations to this package?
More precisely, can it work on both client-rendered or server-rendered React implementations?
It seems to me that it can't, as I get a fatal `Cannot find module "fs"` error while using it with webpack.

**Comment by gre** [comment]
@arnaud this happens if you use webpack. this breaks in linebreak. I have a workaround for this: https://github.com/devongovett/linebreak/issues/1

**Comment by tuxracer** [comment]
@arnaud you must use the brfs loader with webpack https://github.com/Flipboard/react-canvas/issues/102#issuecomment-174345160
