### ISSUE TITLE
Module not found: Error: Cannot resolve module

### ISSUE THREAD

**Issue by super2457** [Flipboard/react-canvas#117]
ERROR in ./~/react-canvas/lib/Surface.js
Module not found: Error: Cannot resolve module 'react/lib/invariant' in E:\xmjApp\node_modules\react-canvas\lib
 @ ./~/react-canvas/lib/Surface.js 5:16-46

ERROR in ./~/react-canvas/lib/ContainerMixin.js
Module not found: Error: Cannot resolve module 'react/lib/emptyObject' in E:\xmjApp\node_modules\react-canvas\lib
 @ ./~/react-canvas/lib/ContainerMixin.js 9:18-50

Thanks in advance for the help!

**Comment by akulov** [comment]
Hi
Same error
What is solution?
