### ISSUE TITLE
Add id, or className to <Surface>

### ISSUE THREAD

**Issue by CharlieGreenman** [Flipboard/react-canvas#136]
I was wondering if architecturally there is a reason why react-canvas does not support putting an id tag or classNames on a <Surface> tag? I would be more than willing to work on it. Thank you :)

**Comment by CharlieGreenman** [comment]
I have created a pull request for this "issue". If you think it is a bad idea, by all means I am more open to other suggestions. Thank you :) 

https://github.com/Flipboard/react-canvas/pull/137

**Comment by Nolski** [comment]
I forgot to mention in the PR but this was resolved in #151

**Comment by tuxracer** [comment]
awesome thanks @Nolski!
