### ISSUE TITLE
Cross Origin getting Images is not supported!

### ISSUE THREAD

**Issue by georgeshevtsov** [Flipboard/react-canvas#146]
Image from origin 'http://lorempixel.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

This is in any browser and it is soo lame.

**Comment by tuxracer** [comment]
This is an inherent browser limitation with CORS that cannot be addressed by the library. The demos have been updated however to use a CORS friendly image host (lorempixel.com used to be CORS friendly, but not anymore)
