### ISSUE TITLE
I'm having issues with importing the module.

### ISSUE THREAD

**Issue by davesnx** [Flipboard/react-canvas#148]
Hi, 

I found an interesting issue, and could be more for my curiosity, but I'm using ES6 with babel.

So I could import the module like that:

``` js
import { Surface, Group, Image, Text, FontFace } from 'react-canvas'
```

and use all of the Components that react-canvas provide. But, I didn't get any error It's just doesn't render. But... If I'm importing first the default and then I get the objects, everything works fine.
(isn't the spread operator, btw).

``` js
import ReactCanvas from 'react-canvas'
const { Surface, Group, Image, Text, FontFace } = ReactCanvas
```

I didn't check how the export works here, but seems that something weird is happening on the `module.export`.

**Comment by davesnx** [comment]
Nothing @tuxracer or @darkyen or @codrin-iftimie'

**Comment by codrin-iftimie** [comment]
Works on my [end](https://github.com/codrin-iftimie/react-canvas/tree/babel_example). you can clone the repo in order to see for yourself.

Maybe there is a problem with `babel`. Can you give me more info about your webpack config file?

**Comment by davesnx** [comment]
Let me try this weekend and I will tell! 
Thanks for respond @codrin-iftimie
