### ISSUE TITLE
Module not found: Error: Cannot resolve module 'transform'

### ISSUE THREAD

**Issue by Nolski** [Flipboard/react-canvas#150]
Hi,

I'm using webpack with babel and ES6 + JSX compilation to compile an app and I wanted to take up react-canvas as a module to depend on. I'm having a bit of trouble getting it to compile using webpack. I'm getting the error below.

```shell
ERROR in /Users/nolski/code/.../~/react-canvas/lib/ReactCanvas.js
Module not found: Error: Cannot resolve module 'transform' in /Users/nolski/code/.../node_modules/react-canvas/lib
 @ /Users/nolski/code/.../~/react-canvas/lib/ReactCanvas.js 14:15-39
```

I have installed the required dependencies as listed in the README and I think I wrote my webpack.config.js file correctly. Am I missing something?

```javascript
module.exports = {
    entry: './app.jsx',
    output: {
        filename: '../pages/queuepage.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel',
                query: {
                    presets: ['react', 'es2015'],
                    retainLines: true
                }
            },
        ],
        postLoaders: [
            { loader: "transform?brfs" }
        ]
    },
    resolve: {
        // you can now require('file') instead of require('file.jsx')
        extensions: ['', '.js', '.json', '.jsx']
    },
    devtool: 'source-map'
};
```

**Comment by yursile** [comment]
i think jsx-loader is required
here is my config:
```
{
                test: /\.js[x]?$/,
                exclude: /node_modules/,
                loader: 'react-hot!jsx!babel?presets[]=es2015,presets[]=react,presets[]=stage-0'
            },
```

**Comment by Nolski** [comment]
@yursile I'm not quite sure I understand. babel currently compiles the ES6 jsx. By the time it hits the transform-brfs loader it should no longer be jsx.

**Comment by Nolski** [comment]
Looks like react-canvas wasn't installed (end of the day mistake I guess) Sorry!

**Comment by yursile** [comment]
hello,I got the same problem with you,(parden me I haven't get you mean before), and I resovle it by  
`npm install -g transform-loader`. hope help you
