### ISSUE TITLE
Rotten Tomatoes Sample App

### ISSUE THREAD

**Issue by VivekPanyam** [Flipboard/react-canvas#17]
This isn't really an issue, but I wasn't sure how to get in touch. I built a Rotten Tomatoes app to try out React Canvas and thought people would be interested in looking at scroll performance.

The demo is at http://vivekpanyam.com/samples/reactcanvas/

**Comment by mjohnston** [comment]
Nice!! This is pretty slick. Is the source on GitHub somewhere? There might be some opportunities to make it even faster.

**Comment by VivekPanyam** [comment]
Thanks! I'll put the source up soon. One of the things I've noticed is that even if you preload the images, there is still a delay + fade in? Any idea what's causing that?

**Comment by mjohnston** [comment]
Hmm I haven't noticed that before. None of the examples preload images, but we do on flipboard.com. I'll try and debug if you have a reproducible case when the code is up.

There currently is no minified build. I presume you mean something you could `bower install` or simply import with a `<script>` tag? Right now, the best way to consume React Canvas is with a module bundler like webpack or browserify. If it would be useful to have a standalone build, I can make it happen.

**Comment by VivekPanyam** [comment]
I think it would be useful to have a standalone build. It would also make it easier for people who are trying to just use React Canvas without modifying it.

I'll comment here with a link to the repo once it's up.

**Comment by VivekPanyam** [comment]
https://github.com/VivekPanyam/RottenTomatoesSample

**Comment by mjohnston** [comment]
Good stuff! I created a PR on RottenTomatoesSample, so will close this issue out.

**Comment by mrwade** [comment]
+1 for bower or standalone build

**Comment by bradens** [comment]
+1 for standalone build

**Comment by differui** [comment]
+1 for standalone build
