### ISSUE TITLE
impossible to npm install

### ISSUE THREAD

**Issue by aestheticsdata** [Flipboard/react-canvas#18]
when doing npm install :
npm ERR! git clone git://github.com/mjohnston/scroller Cloning into bare repository '/Users/cosmocat/.npm/_git-remotes/git-github-com-mjohnston-scroller-440e2a6b'...
npm ERR! git clone git://github.com/mjohnston/scroller fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/mjohnston/scroller github.com[0: 192.30.252.129]: errno=Operation timed out
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/cosmocat/.npm/_git-remotes/_templates --mirror git://github.com/mjohnston/scroller /Users/cosmocat/.npm/_git-remotes/git-github-com-mjohnston-scroller-440e2a6b
npm ERR! Cloning into bare repository '/Users/cosmocat/.npm/_git-remotes/git-github-com-mjohnston-scroller-440e2a6b'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Operation timed out

**Comment by kfrackiewicz** [comment]
Probably you are  behind firewall. Try clone thru https:

git clone https://github.com/mjohnston/scroller

**Comment by mjohnston** [comment]
Yes, it is likely a firewall issue. This might help you out:
https://github.com/npm/npm/issues/5257#issuecomment-60441477

**Comment by aestheticsdata** [comment]
Thanx. It works.
