### ISSUE TITLE
onClick on listview example broken

### ISSUE THREAD

**Issue by brentvatne** [Flipboard/react-canvas#22]
Modified the code on `Item` to:

```javascript
  onGroupClick: function() {
    console.log(this.props.title);
  },

  render: function () {
    return (
      <Group style={this.getStyle()} onClick={this.onGroupClick}>
        <Image style={this.getImageStyle()} src={this.props.imageUrl} />
        <Text style={this.getTitleStyle()}>{this.props.title}</Text>
      </Group>
    );
  },
```
([link to forked repo with this code](https://github.com/brentvatne/react-canvas))

When I click on the first item in the list, it seems to think that I'm clicking on another item. No other items respond to click, just the first.

![screen shot 2015-02-12 at 1 52 35 pm](https://cloud.githubusercontent.com/assets/90494/6177840/99c88462-b2be-11e4-940b-e4fbfc7fe446.png)

(start! and end! are just statements that I inserted on touchstart and touchend)

`onClick` works as expected on the `Group` components of the timeline example, however.

**Comment by brentvatne** [comment]
I investigated this and found that because it is because `translateY` is used in the listview and the current hit detection mechanism only incorporates the`top` and `left` styles. So all of the items appeared to be in the top position, and the last one was always considered to be clicked. I modified this to add a `hitFrame` property to layers in order to incorporate the sum of the current layer and parent layers' X/Y translations and it now works as expected on both examples. Open to a more elegant solution, of course.

[See my attempt at a fix in this commit](https://github.com/brentvatne/react-canvas/commit/2a3aefa2874560225a77b80704557550b5ec75b9)

**Comment by amullins83** [comment]
#23 worked for me.

**Comment by mjohnston** [comment]
Argh - the hit detection code must not have been completely moved into react-canvas from flipboard.com.

@brentvatne Thanks for investigating. You're precisely right! Though I think we can do the frame resolution at hit test. Fix incoming.
