### ISSUE TITLE
Timeline without image

### ISSUE THREAD

**Issue by Zwergal** [Flipboard/react-canvas#25]
I cloned the repo and the timeline example works fine. I want to have a text only timeline so the same as the example just except the image. But as soon as I remove the image from the timeline example, the scrolling doesn't work anymore. Do I miss something? Do I need to add a Layer instead of the image, or is this a bug?

**Comment by mjohnston** [comment]
No, this is a bug. Pretty sure I know what's going on - will have a fix soon.
