### ISSUE TITLE
Building a UI with layers

### ISSUE THREAD

**Issue by zoomclub** [Flipboard/react-canvas#27]
Is it possible to create a simple app that uses layers for different aspects of the interactive UI? React-Canvas looks like it is flexible enough for what I have in mind but it is also quite abstracted, likely in order to be an optimal 60fps solution.

Its a good thing I was already calling my apex component the surface. My surface would require different layers for different aspects of rendering and editing. Here is how I envision the layer stack:

surface-container
    • background-commit-layer
    • foreground-commit-layer
    • tool-editing-layer
    • tool-reporting-layer
    • config-form-layer

The commit layers have a canvas each. Tool edited data would be rendered here, with the background layer rendering data that does not change to often and the foreground layer rendering data that changes more often. These layers optimize the amount of rendering required and serve as useful aspects of the final product the app editing produces.

The tool editing layer renders items during editing, once the editing is complete and accepted the commit layers would update. The report layer draws useful tool data while tools are used, so this has its own layer. These are both canvas based layers.

The config form layer is the only one that is more DOM based. Essentially it is only used to edit various states and styles for the different components in the app, react-router can be used here to manage the different config panels.

These layers would fill the complete app frame and be arranged by z-index and have their own alpha transparency settings or be hidden altogether until some tool brings them forward.

Within the two tool related layers there would also be children components for different editors. I'm assuming that React-Canvas components can contain a mix of canvas or DOM based components.

Is this humble layered app design possible? It looks like the Surface has one base RenderLayer. How do more RenderLayers get added as children of the base RenderLayer? Not sure the Image and Text layers alone are right for defining my apps layer stack?

It certainly would be helpful to understand the React-Canvas API from the perspective described above then move on from there. I have a hunch that React-Canvas can do many things. Its just a matter of grounding the abstractions in something I know.

**Comment by mjohnston** [comment]
It's a bit hard to envision the whole picture you have in mind... but I think I understand the general idea.

You can mix and match React Canvas components with standard DOM components, e.g. the editing controls. Input events are bound to the root <Surface> so as long as the components are stacked accordingly with positioning and z-index this should work.

You cannot currently render a non-Layer component inside a Surface. If you have a specific use case in mind, let me know, but I think you should be able to accomplish most things with the above stacking approach.

There really is not much to the React Canvas API, by design. They're just components which can be composed like standard React DOM components. You can certainly add more than one child to a layer. Take a look at <Group> which can be used for this purpose.

To your point about Text and Image components not being sufficient for your purpose, it's possible we might be adding more primitives in the future. What other kind of elements did you have in mind?

**Comment by zoomclub** [comment]
The app layer stack I have in mind would be for a tablet or desktop app. Essentially it is stack of canvases where each is one of the first four layers listed above. Then there would be a component for editing the configs in a form based layout that would be similar to a modal dialog or a portal. 

Maybe this can be done with just two major layers, one is a React-Canvas layer (Surface) containing stacked canvases and the other is a standard React component that uses JSX to define its layout?

Could the stack of canvases in the major Surface layer be just a Group of Image components? Except I intend to paint the images in each canvas using font glyphs and canvas primitives. I would need blank canvases I can directly draw on. I refer to these canvases as layers but they might not need to be React-Canvas layers then, just named canvases I can access and direct rendering to?

You mention that the input events are bound to the root (base RenderLayer) so that would mean they capture event types for all canvases in the Surface, right? This might be alright because the bound to handlers can each do their thing based on state, which depends on what tool is active.

If I understand right React-Canvas components can be used inside other React components but standard React components can not work inside React-Canvas components? I'm not yet sure I need other React-Canvas components. I mainly need to draw directly to the canvases in a Surface.

Other than that I setup I can see making use of ListViews for palette components, etc. Maybe that is the right way to think about React-Canvas? Presently, I'm thinking of it as the top level container for the whole app.

**Comment by mjohnston** [comment]
Wow, a lot to digest here :) Interested in taking this further offline. Reach me at mj@flipboard.com
