### ISSUE TITLE
[Enhancement]: Ability to use a router

### ISSUE THREAD

**Issue by darkyen** [Flipboard/react-canvas#36]
Any real world application would need one, or some way to do so.

There are many react routers currently existent, I used this one https://github.com/rackt/react-router
 

The current way i could think off was rendering a canvas inside a route and then binding this on the top but that broke transitions :-/ 

second method I thought ( which works now) is having the router write an empty url then accessing the route via a store ( flux !!), but that is just too ugly.

**Comment by mjohnston** [comment]
You should be able to use any router with React Canvas. The difficultly is that React Canvas relies on React 0.13.x which is in beta. If you have a specific example where rendering a Surface inside a route is breaking I would love to see it.

FWIW flipboard.com uses the flux pattern in combination with Page.js.

**Comment by darkyen** [comment]
So pretty much the way i did is the way to go so-far ;-D enough for me :-)

there isn't anything breaking it, the problem I faced is it felt quite wrong doing animations that way, I believe core-animation-pages (polymer) style animations should be more possible and declaratively possible with react and react-pages will make it butter smooth.
