### ISSUE TITLE
Top <Image /> half is cut off

### ISSUE THREAD

**Issue by mbrgm** [Flipboard/react-canvas#43]
I encounter the following result of the css-layout example in all three Chrome Canary, Safari and Firefox. The same happens to my own images.

![bildschirmfoto 2015-02-17 um 20 16 04](https://cloud.githubusercontent.com/assets/2971615/6235325/f951a694-b6e1-11e4-8c96-fe57317d4d99.png)

**Comment by mjohnston** [comment]
I noticed that too but haven't had a chance yet to look at it. I suspect it's related to a recent change I made to better animate images with transparency, which added an opaque background layer. <Image> now has 2 children: the background and the actual image. Guessing the flexbox styles are assigning them equal weight so they are stacked.

**Comment by mbrgm** [comment]
I have to admit I either could not reproduce or did not understand the problem described in #16. So I added this quick fix for my own use. One would have to layer the background layer and image properly to fix this issue, but this would involve calculating the position for absolute positioning manually.

Could the additional background layer be removed from the virtual dom and only be added when actually drawing on the canvas? I guess this would solve both problems?

**Comment by mbrgm** [comment]
I fixed this directly in the canvas drawing layer. Gonna submit the PR today after work.
