### ISSUE TITLE
Is this better than dom?

### ISSUE THREAD

**Issue by ccorcos** [Flipboard/react-canvas#71]
I'm very intrigued with this project but I'm curious, other than accessibility, is there any reason this isn't a better solution than DOM? What is currently challenging with this technology thats much easier via dom (assuming we're making a self-contained app, not a traditional website).

**Comment by ccorcos** [comment]
I'm considering building an entire mobile app using this (just for fun ;) but am I going to run into any serious problems?

**Comment by mjohnston** [comment]
It's not meant to completely replace DOM-based rendering, which is still needed for text input, copy/paste, accessibility and SEO.

I wouldn't suggest building an entire app in react-canvas for these reasons. At Flipboard, it solved a very specific use case for us where DOM-based rendering wasn't sufficient. We use a combination of canvas and DOM-based rendering.

**Comment by ccorcos** [comment]
Awesome. That's what I needed to hear. I really like how React abstracts UIs. It seems inevitable that UIs will be rebuild from the ground up through OpenGL or something using React.
