### ISSUE TITLE
peerDependency causes issues

### ISSUE THREAD

**Issue by pburtchaell** [Flipboard/react-canvas#74]
Does this component really depend on Does react-canvas really depend on React `v0.13.0-beta.1`? When installed with other commonly used React modules from npm (react-router, react-hot-loader, etc.) this causes npm to be unable to resolve which version of React to use.

For example:
```
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@0.11.6 wants react@0.12.x
npm ERR! peerinvalid Peer react-canvas@0.0.1 wants react@^0.13.0-beta.1
npm ERR! peerinvalid Peer react-hot-loader@1.1.5 wants react@>=0.11.0 || >=0.13.0-beta.1
```

If react-canvas actually does depend on the beta version of React and the beta version *only*, then I would update the README to let users know this. Otherwise, I would suggest updating the value of the [peerDependency](https://github.com/Flipboard/react-canvas/blob/master/package.json#L37) property to be `>=0.11.x || 0.13.0-beta.1` in order to enable npm to properly resolve React.

If you are open to this change, I can make a PR.

**Comment by mjohnston** [comment]
I believe we could move it to 0.12.x but no lower. 0.12 introduced significant changes to the component model which react-canvas relies on for the drawing engine integration.

See: http://facebook.github.io/react/blog/2014/10/28/react-v0.12.html

I haven't tested with 0.12.x though. If you're up for verifying it works with 0.12.x a PR would be much appreciated.

**Comment by pburtchaell** [comment]
Now that 0.13.x [has been released](http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html) I think you could probably just change the dependency over to that to solve the problem. Most other libs should also be upgrading to 0.13.x so I don't think the peerDependency conflict will occur.

**Comment by mjohnston** [comment]
Good point.
