### ISSUE TITLE
Image component doesn't rerender

### ISSUE THREAD

**Issue by ingojoseph** [Flipboard/react-canvas#77]
`<Image src={src} />`

If I change the variable `src` the image doesn't update. Is this a bug?

**Comment by benjamingeorge** [comment]
I have a similar problem and I'm wondering if I'm missing something.  When I change the src on an image component via a state change, it doesn't rerender on the canvas.  Isn't this the expected behavior or no?

**Comment by ingojoseph** [comment]
@benjamingeorge Yes, if you change the state, all components should update. That's the common behavior of React components.

You can try to use my fix but I just noticed that it's not working perfectly if the image is not loaded already.

**Comment by benjamingeorge** [comment]
Yes your fix works for me but only if the images are preloaded by placing them in the DOM in img tags.

**Comment by mattrei** [comment]
Is it possible to fix this bug somehow? Such a showstopper for me. 
Thanks

**Comment by singggum3b** [comment]
+1, you can workaround by using src (or a hash of src) as key
